package tw.everest.fdti;

public class Util {

	public final static long FT_OK=0,
	FT_INVALID_HANDLE=1,
	FT_DEVICE_NOT_FOUND=2,
	FT_DEVICE_NOT_OPENE=3,
	FT_IO_ERROR=4,
	FT_INSUFFICIENT_RESOURCES=5,
	FT_INVALID_PARAMETER=6,
	FT_INVALID_BAUD_RATE=7,
	FT_DEVICE_NOT_OPENED_FOR_ERASE=8,
	FT_DEVICE_NOT_OPENED_FOR_WRITE=9,
	FT_FAILED_TO_WRITE_DEVICE=10,
	FT_EEPROM_READ_FAILED=11,
	FT_EEPROM_WRITE_FAILED=12,
	FT_EEPROM_ERASE_FAILED=13,
	FT_EEPROM_NOT_PRESENT=14,
	FT_EEPROM_NOT_PROGRAMMED=15,
	FT_INVALID_ARGS=16,
	FT_NOT_SUPPORTED=17,
	FT_OTHER_ERROR=18,
	FT_DEVICE_LIST_NOT_READY=19,
	FT_INIT=20;
	
	public final static int MAX_SEND_DATA_BYTE=250;
	
	public final static String RM_RADIO_ERR="radio_err",
			RM_OK="ok",
			RM_INVALID_PARAM="invalid_param",
			RM_BUSY="bust",
			RM_RADIO_RX="radio_rx",
			RM_RADIO_TX="radio_tx_ok";
	
}
